### ISSUE TITLE
Page builder preview problem.

### ISSUE THREAD

**Issue by ytingchou** [ridwanskaterock/cicool#222]
Environment:
1. OS: macOS 10.12.6
2. Browser: Google Chrome version 70.0.3538.54

When trying to preview new page on page builder, you can see the following error on javascript console.

```
jquery-iframe-auto-height.js:97 Uncaught DOMException: Blocked a frame with origin "http://cicool.heriver.com" from accessing a cross-origin frame.
    at HTMLIFrameElement.<anonymous> (http://cicool.heriver.com/asset/iframe-auto/src/jquery-iframe-auto-height.js:97:66)
    at Function.each (http://cicool.heriver.com/asset//admin-lte/plugins/jQuery/jquery-2.2.3.min.js:2:2861)
    at n.fn.init.each (http://cicool.heriver.com/asset//admin-lte/plugins/jQuery/jquery-2.2.3.min.js:2:845)
    at n.fn.init.$.fn.iframeAutoHeight (http://cicool.heriver.com/asset/iframe-auto/src/jquery-iframe-auto-height.js:55:17)
    at HTMLIFrameElement.<anonymous> (http://cicool.heriver.com/asset/js/page.js:141:35)
    at HTMLIFrameElement.dispatch (http://cicool.heriver.com/asset//admin-lte/plugins/jQuery/jquery-2.2.3.min.js:3:7537)
    at HTMLIFrameElement.r.handle (http://cicool.heriver.com/asset//admin-lte/plugins/jQuery/jquery-2.2.3.min.js:3:5620)
```

This issue can be reproduced on the demo website (http://cicool.heriver.com/administrator/login) as well.

**Comment by ridwanskaterock** [comment]
Thanks for report i will check for it
