### ISSUE TITLE
Error generating TOKEN

### ISSUE THREAD

**Issue by inglesuniversal** [ridwanskaterock/cicool#227]
{
-"errors": [
-{
"type": "Whoops\\Exception\\ErrorException",
"message": "Uncaught Exception: Error: Call to a member function pushHandler() on null in /var/www/html/cicool/application/core/My_Exceptions.php:56\nStack trace:\n#0 /var/www/html/cicool/system/core/Common.php(623): My_Exceptions->show_php_error(2, 'Illegal string ...', '/var/www/html/c...', 848)\n#1 /var/www/html/cicool/application/helpers/app_helper.php(848): _error_handler(2, 'Illegal string ...', '/var/www/html/c...', 848, Array)\n#2 /var/www/html/cicool/application/core/My_Controller.php(881): getallheaders()\n#3 /var/www/html/cicool/application/core/My_Controller.php(870): API->getHeader('X-Api-Key')\n#4 /var/www/html/cicool/application/core/My_Controller.php(841): API->jwtGetKey()\n#5 /var/www/html/cicool/application/controllers/api/User.php(102): API->jwtEncode(Array)\n#6 /var/www/html/cicool/application/libraries/REST_Controller.php(723): User->request_token_post()\n#7 /var/www/html/cicool/system/core/CodeIgniter.php(532): REST_Controller->_remap('request_token', Array)\n#8 /var/www/html/cicool/index.php(335): require_on",
"file": "/var/www/html/cicool/application/core/My_Exceptions.php",
"line": 18
}
]
}

**Comment by ridwanskaterock** [comment]
Can i see your request token for that i can see parameters and header for it ? 

THanks

**Comment by inglesuniversal** [comment]
My dear friend: I regret to tell you that due to the errors from the script purchased from you that made me delay my delivery date. My boss has cancelled the project, so according to CodeCanyon policies I would like to request a refund. Can you kindly provide me with a refund link?

Best regards

**Comment by ridwanskaterock** [comment]
Hi I can't accept your request based on our policy to publish the requirements of this software also in the version of the description and documentation 

you can see on descrioption https://codecanyon.net/item/cicool-page-form-rest-api-and-crud-generator/19207897

Thanks

**Comment by inglesuniversal** [comment]
ok my boss has agreed that you help us make sure the script runs smoothly in the following days? Is there a way to easily test all the features are fully functional?

**Comment by ridwanskaterock** [comment]
Currently i am not implemented for PHPUnit Test on this project, but for API you can check using postman or using resttool on Cicool project
